### ISSUE TITLE
In Requirements.txt Streamlit must be set to streamlit==1.22.0 to avoid error

### ISSUE THREAD

**Issue by menelic** [jojojaeger/asr#2]
I had to set streamlit to streamlit==1.22.0  to avid a ModuleNotFoundError: No module named ‘altair.vegalite.v4 error. Once this change is made, whisper-streamlit installs.

**Comment by jojojaeger** [comment]
thanks i will update that!

**Comment by menelic** [comment]
I submitted #5 for that
